# Generated by Django 3.2.4 on 2023-01-24 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('urlimagen', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('urlmapa', models.TextField()),
            ],
        ),
    ]
